spring.application.name=BitFinanace

# Docker Compose
spring.docker.compose.enabled=false

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/bitfinance
spring.data.mongodb.database=bitfinance

# Binance WebSocket
binance.websocket.url=wss://stream.binance.com:9443/ws/btcusdt@trade
